name: Modelops deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: hello-modelops-world
      run: echo "hello modelops workflow …"
    - name: python version
      run: python --version
    - name: install python requirements
      run: pip install -r requirements.txt

